# Generated by Django 4.0.6 on 2022-07-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('cantidad_pasajeros', models.IntegerField()),
                ('fecha_salida', models.DateField()),
            ],
        ),
    ]
